test PR to trigger build action
kieler/elkjs pull request #288
Opened 2024-07-02 13:57 UTC by Eddykasp

2024-07-02 14:13 UTC, Eddykasp commented
this confirms that the problem appears to limited to disco and its CompactionStrategy

2024-07-02 14:42 UTC, soerendomroes commented
Does this mean we remove disco? Or that disco just cannot be transpiled to JavaScript?

2024-07-02 14:59 UTC, Eddykasp commented
Removing it would fix the CI build on Github but since I can still build it locally, I don't think we should jump straight to removing it completely. But it's an option to keep in mind I guess

2024-07-03 11:53 UTC, soerendomroes requested changes

2024-07-03 11:53 UTC, soerendomroes commented on build.gradle
> +  //"${elkRepo}/plugins/org.eclipse.elk.alg.disco/src",
Maybe add a comment why this is not included here and maybe a FIXME to investifate the problem.

2024-07-03 11:53 UTC, soerendomroes commented on src/java/org/eclipse/elk/js/ElkJs.java
> +//import org.eclipse.elk.alg.disco.options.*;
See above

2024-07-03 11:53 UTC, soerendomroes commented on src/java/org/eclipse/elk/js/ElkJs.java
> +   //         } else if (alg.equals("disco")) {
See above

2024-07-04 10:59 UTC, soerendomroes approved these changes

2024-07-04 11:17 UTC, merged